name: Create environment 

on:
  push:
    paths:
      - Dockerfile
      - config/*
      - .github/workflows/environment.yml
      - bin/*
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    container: philipssoftware/node:lts

    steps:
      - name: Checkout Continuous Compliance 
        uses: actions/checkout@v3

      - name: Build Docker Images
        uses: philips-software/docker-ci-scripts@v4.5.1
        with:
          dockerfile: .
          image-name: continuous-compliance
          tags: latest 0.1
          push-branches: main develop
          sign: true
          sbom: true
          slsa-provenance: true
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY: ghcr.io/philips-labs
          GITHUB_ORGANIZATION: philips-labs
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PUBLIC_KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}
